-- begin BYTESVC_ORDER
alter table BYTESVC_ORDER add constraint FK_BYTESVC_ORDER_ON_SERVICE_PERSON foreign key (SERVICE_PERSON_ID) references SEC_USER(ID)^
alter table BYTESVC_ORDER add constraint FK_BYTESVC_ORDER_ON_OUTBACK_PERSON foreign key (OUTBACK_PERSON_ID) references SEC_USER(ID)^
create unique index IDX_BYTESVC_ORDER_UNIQ_VIEWABLE_ID on BYTESVC_ORDER (VIEWABLE_ID) ^
create index IDX_BYTESVC_ORDER_ON_SERVICE_PERSON on BYTESVC_ORDER (SERVICE_PERSON_ID)^
create index IDX_BYTESVC_ORDER_ON_OUTBACK_PERSON on BYTESVC_ORDER (OUTBACK_PERSON_ID)^
-- end BYTESVC_ORDER
-- begin BYTESVC_ORDER_WORK
alter table BYTESVC_ORDER_WORK add constraint FK_BYTESVC_ORDER_WORK_ON_ORDER foreign key (ORDER_ID) references BYTESVC_ORDER(ID)^
create index IDX_BYTESVC_ORDER_WORK_ON_ORDER on BYTESVC_ORDER_WORK (ORDER_ID)^
-- end BYTESVC_ORDER_WORK
-- begin BYTESVC_ORDER_SPARE
alter table BYTESVC_ORDER_SPARE add constraint FK_BYTESVC_ORDER_SPARE_ON_ORDER foreign key (ORDER_ID) references BYTESVC_ORDER(ID)^
create index IDX_BYTESVC_ORDER_SPARE_ON_ORDER on BYTESVC_ORDER_SPARE (ORDER_ID)^
-- end BYTESVC_ORDER_SPARE
-- begin BYTESVC_ORDER_EVENT
alter table BYTESVC_ORDER_EVENT add constraint FK_BYTESVC_ORDER_EVENT_ON_ORDER foreign key (ORDER_ID) references BYTESVC_ORDER(ID)^
create index IDX_BYTESVC_ORDER_EVENT_ON_ORDER on BYTESVC_ORDER_EVENT (ORDER_ID)^
-- end BYTESVC_ORDER_EVENT
